version: '3.4'

services:
  docker_db_test:
    image: dalinesterov/docker_db_test
    build: .
    environment:
      - "NODE_ENV:production"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data: